import { SkillItem } from '@/types/calculator.types';

export const AGILITY_ITEMS: SkillItem[] = [
    {
        name: 'Jogging',
        level: 1,
        exp: 30,
        seconds: 6,
        expPerSecond: 5.0,
        goldValue: 0, // No gold value for agility tasks based on the image
        goldPerSecond: 0,
    },
    {
        name: 'Swimming',
        level: 15,
        exp: 40,
        seconds: 7.5,
        expPerSecond: 5.33,
        goldValue: 0,
        goldPerSecond: 0,
    },
    {
        name: 'Monkey Bars',
        level: 30,
        exp: 55,
        seconds: 8.5,
        expPerSecond: 6.47,
        goldValue: 0,
        goldPerSecond: 0,
    },
    {
        name: 'Str Training',
        level: 40,
        exp: 70,
        seconds: 9.5,
        expPerSecond: 7.37,
        goldValue: 0,
        goldPerSecond: 0,
    },
    {
        name: 'Basic Course',
        level: 55,
        exp: 90,
        seconds: 11,
        expPerSecond: 8.18,
        goldValue: 0,
        goldPerSecond: 0,
    },
    {
        name: 'Combat Training',
        level: 70,
        exp: 105,
        seconds: 12.5,
        expPerSecond: 8.4,
        goldValue: 0,
        goldPerSecond: 0,
    },
    {
        name: 'Military Course',
        level: 80,
        exp: 120,
        seconds: 13,
        expPerSecond: 9.23,
        goldValue: 0,
        goldPerSecond: 0,
    },
    {
        name: 'Rock Climbing',
        level: 90,
        exp: 160,
        seconds: 15,
        expPerSecond: 10.67,
        goldValue: 0,
        goldPerSecond: 0,
    },
    {
        name: 'Sunfire Summit',
        level: 105,
        exp: 2520,
        seconds: 262.5,
        expPerSecond: 9.6,
        goldValue: 0,
        goldPerSecond: 0,
    },
];
