import { SkillItem } from '@/types/calculator.types';

export const BREWING_ITEMS: SkillItem[] = [
    {
        name: 'Swiftness',
        level: 1,
        exp: 750,
        seconds: 55,
        expPerSecond: 13.64,
        goldValue: 250,
        goldPerSecond: 4.18,
    },
    {
        name: 'Negotiation',
        level: 15,
        exp: 1045,
        seconds: 65,
        expPerSecond: 16.08,
        goldValue: 350,
        goldPerSecond: 5.4,
    },
    {
        name: 'Resurrection',
        level: 30,
        exp: 1215,
        seconds: 72.5,
        expPerSecond: 16.76,
        goldValue: 425,
        goldPerSecond: 5.9,
    },
    {
        name: 'Forgery',
        level: 45,
        exp: 1515,
        seconds: 85,
        expPerSecond: 17.82,
        goldValue: 575,
        goldPerSecond: 6.8,
    },
    {
        name: 'Great Sight',
        level: 55,
        exp: 1950,
        seconds: 97.5,
        expPerSecond: 20.0,
        goldValue: 650,
        goldPerSecond: 6.7,
    },
    {
        name: 'Trickery',
        level: 65,
        exp: 2445,
        seconds: 115,
        expPerSecond: 21.26,
        goldValue: 725,
        goldPerSecond: 6.3,
    },
    {
        name: 'Dark Magic',
        level: 75,
        exp: 2950,
        seconds: 132.5,
        expPerSecond: 22.26,
        goldValue: 800,
        goldPerSecond: 6,
    },
    {
        name: 'Pure Power',
        level: 85,
        exp: 3750,
        seconds: 155,
        expPerSecond: 24.19,
        goldValue: 900,
        goldPerSecond: 6,
    },
    {
        name: 'Ancient Knowledge',
        level: 93,
        exp: 5025,
        seconds: 180,
        expPerSecond: 27.92,
        goldValue: 1000,
        goldPerSecond: 5.6,
    },
    {
        name: 'Dragonfire Potion',
        level: 105,
        exp: 2950,
        seconds: 90,
        expPerSecond: 32.78,
        goldValue: 2500,
        goldPerSecond: 27.78,
    },
];
