import { SkillItem } from '@/types/calculator.types';

// Add goldCost field manually for carpentry items
interface CarpentryItem extends SkillItem {
    goldCost: number;
}

export const CARPENTRY_ITEMS: CarpentryItem[] = [
    {
        name: 'Spruce',
        level: 1,
        exp: 40,
        seconds: 9,
        expPerSecond: 4.44,
        goldValue: 35,
        goldPerSecond: 3.9,
        goldCost: 50,
    },
    {
        name: 'Pine',
        level: 10,
        exp: 45,
        seconds: 9,
        expPerSecond: 5.0,
        goldValue: 45,
        goldPerSecond: 5,
        goldCost: 60,
    },
    {
        name: 'Oak',
        level: 20,
        exp: 50,
        seconds: 9,
        expPerSecond: 5.56,
        goldValue: 55,
        goldPerSecond: 6,
        goldCost: 70,
    },
    {
        name: 'Maple',
        level: 30,
        exp: 55,
        seconds: 9,
        expPerSecond: 6.11,
        goldValue: 65,
        goldPerSecond: 7,
        goldCost: 80,
    },
    {
        name: 'Teak',
        level: 40,
        exp: 60,
        seconds: 9,
        expPerSecond: 6.67,
        goldValue: 75,
        goldPerSecond: 8,
        goldCost: 90,
    },
    {
        name: 'Chestnut',
        level: 50,
        exp: 70,
        seconds: 9,
        expPerSecond: 7.78,
        goldValue: 85,
        goldPerSecond: 9,
        goldCost: 100,
    },
    {
        name: 'Mahogany',
        level: 60,
        exp: 80,
        seconds: 9,
        expPerSecond: 8.89,
        goldValue: 95,
        goldPerSecond: 11,
        goldCost: 110,
    },
    {
        name: 'Yew',
        level: 70,
        exp: 95,
        seconds: 9,
        expPerSecond: 10.56,
        goldValue: 110,
        goldPerSecond: 12,
        goldCost: 125,
    },
    {
        name: 'Redwood',
        level: 80,
        exp: 140,
        seconds: 12,
        expPerSecond: 11.67,
        goldValue: 155,
        goldPerSecond: 13,
        goldCost: 150,
    },
    {
        name: 'Magical',
        level: 90,
        exp: 200,
        seconds: 15,
        expPerSecond: 13.33,
        goldValue: 210,
        goldPerSecond: 14,
        goldCost: 175,
    },
    {
        name: 'Ignis Heartwood',
        level: 105,
        exp: 2000,
        seconds: 131.25,
        expPerSecond: 15.24,
        goldValue: 375,
        goldPerSecond: 2.86,
        goldCost: 175,
    },
];
