import { SkillItem } from '@/types/calculator.types';

// Fish category
export const FISH_ITEMS: SkillItem[] = [
    {
        name: 'Piranha',
        level: 1,
        exp: 10,
        seconds: 3,
        expPerSecond: 3.33,
        goldValue: 6,
        goldPerSecond: 2,
        category: 'Fish',
    },
    {
        name: 'Perch',
        level: 10,
        exp: 16,
        seconds: 3.5,
        expPerSecond: 4.57,
        goldValue: 10,
        goldPerSecond: 2.9,
        category: 'Fish',
    },
    {
        name: 'Mackerel',
        level: 15,
        exp: 20,
        seconds: 4,
        expPerSecond: 5.0,
        goldValue: 12,
        goldPerSecond: 3,
        category: 'Fish',
    },
    {
        name: 'Cod',
        level: 20,
        exp: 26,
        seconds: 4.5,
        expPerSecond: 5.78,
        goldValue: 15,
        goldPerSecond: 3.3,
        category: 'Fish',
    },
    {
        name: 'Trout',
        level: 25,
        exp: 33,
        seconds: 5,
        expPerSecond: 6.6,
        goldValue: 18,
        goldPerSecond: 3.6,
        category: 'Fish',
    },
    {
        name: 'Salmon',
        level: 30,
        exp: 40,
        seconds: 6,
        expPerSecond: 6.67,
        goldValue: 18,
        goldPerSecond: 3,
        category: 'Fish',
    },
    {
        name: 'Carp',
        level: 40,
        exp: 56,
        seconds: 7.5,
        expPerSecond: 7.47,
        goldValue: 20,
        goldPerSecond: 2.7,
        category: 'Fish',
    },
    {
        name: 'Zander',
        level: 50,
        exp: 80,
        seconds: 10,
        expPerSecond: 8.0,
        goldValue: 25,
        goldPerSecond: 2.5,
        category: 'Fish',
    },
    {
        name: 'Pufferfish',
        level: 60,
        exp: 105,
        seconds: 12.5,
        expPerSecond: 8.4,
        goldValue: 34,
        goldPerSecond: 2.7,
        category: 'Fish',
    },
    {
        name: 'Anglerfish',
        level: 70,
        exp: 155,
        seconds: 17.5,
        expPerSecond: 8.86,
        goldValue: 55,
        goldPerSecond: 3.1,
        category: 'Fish',
    },
    {
        name: 'Tuna',
        level: 85,
        exp: 255,
        seconds: 26.25,
        expPerSecond: 9.71,
        goldValue: 75,
        goldPerSecond: 2.9,
        category: 'Fish',
    },
    {
        name: 'Bloodmoon eel',
        level: 95,
        exp: 892,
        seconds: 90,
        expPerSecond: 9.91,
        goldValue: 40,
        goldPerSecond: 0.5,
        category: 'Fish',
    },
];

// Meat category
export const MEAT_ITEMS: SkillItem[] = [
    {
        name: 'Meat',
        level: 10,
        exp: 30,
        seconds: 2.5,
        expPerSecond: 12.0,
        goldValue: 20,
        goldPerSecond: 8,
        category: 'Meat',
    },
    {
        name: 'Giant Meat',
        level: 30,
        exp: 60,
        seconds: 4,
        expPerSecond: 15.0,
        goldValue: 60,
        goldPerSecond: 15,
        category: 'Meat',
    },
    {
        name: 'Quality Meat',
        level: 60,
        exp: 120,
        seconds: 6,
        expPerSecond: 20.0,
        goldValue: 90,
        goldPerSecond: 15,
        category: 'Meat',
    },
    {
        name: 'Superior Meat',
        level: 90,
        exp: 250,
        seconds: 10,
        expPerSecond: 25.0,
        goldValue: 150,
        goldPerSecond: 15,
        category: 'Meat',
    },
    {
        name: 'Apex Meat',
        level: 100,
        exp: 350,
        seconds: 12,
        expPerSecond: 29.17,
        goldValue: 250,
        goldPerSecond: 20.83,
        category: 'Meat',
    },
];

// Dishes category
export const DISHES_ITEMS: SkillItem[] = [
    {
        name: 'Potato Soup',
        level: 15,
        exp: 40,
        seconds: 2.5,
        expPerSecond: 16.0,
        goldValue: 35,
        goldPerSecond: 14,
        category: 'Dishes',
    },
    {
        name: 'Meat Burger',
        level: 25,
        exp: 75,
        seconds: 4,
        expPerSecond: 18.75,
        goldValue: 40,
        goldPerSecond: 10,
        category: 'Dishes',
    },
    {
        name: 'Cod Soup',
        level: 40,
        exp: 150,
        seconds: 5.5,
        expPerSecond: 27.27,
        goldValue: 55,
        goldPerSecond: 10,
        category: 'Dishes',
    },
    {
        name: 'Blueberry Pie',
        level: 50,
        exp: 200,
        seconds: 6,
        expPerSecond: 33.33,
        goldValue: 70,
        goldPerSecond: 11.7,
        category: 'Dishes',
    },
    {
        name: 'Salmon Salad',
        level: 60,
        exp: 250,
        seconds: 7,
        expPerSecond: 35.71,
        goldValue: 105,
        goldPerSecond: 15,
        category: 'Dishes',
    },
    {
        name: 'Porcini Soup',
        level: 70,
        exp: 400,
        seconds: 8,
        expPerSecond: 50.0,
        goldValue: 175,
        goldPerSecond: 21.9,
        category: 'Dishes',
    },
    {
        name: 'Beef Stew',
        level: 80,
        exp: 550,
        seconds: 9,
        expPerSecond: 61.11,
        goldValue: 225,
        goldPerSecond: 25.0,
        category: 'Dishes',
    },
    {
        name: 'Power Pizza',
        level: 95,
        exp: 750,
        seconds: 10,
        expPerSecond: 75.0,
        goldValue: 525,
        goldPerSecond: 52.5,
        category: 'Dishes',
    },
];

// Combined cooking items
export const COOKING_ITEMS: SkillItem[] = [
    ...FISH_ITEMS,
    ...MEAT_ITEMS,
    ...DISHES_ITEMS,
];
