import { SkillItem } from '@/types/calculator.types';

export const FARMING_ITEMS: SkillItem[] = [
    {
        name: 'Potato',
        level: 1,
        exp: 75,
        seconds: 30,
        expPerSecond: 2.5,
        goldValue: 250,
        goldPerSecond: 8.3,
    },
    {
        name: 'Carrot',
        level: 10,
        exp: 200,
        seconds: 40,
        expPerSecond: 5.0,
        goldValue: 375,
        goldPerSecond: 9.4,
    },
    {
        name: 'Tomato',
        level: 20,
        exp: 300,
        seconds: 60,
        expPerSecond: 6.0,
        goldValue: 550,
        goldPerSecond: 9.2,
    },
    {
        name: 'Cabbage',
        level: 25,
        exp: 325,
        seconds: 60,
        expPerSecond: 5.42,
        goldValue: 750,
        goldPerSecond: 12.5,
    },
    {
        name: 'Strawberry',
        level: 35,
        exp: 500,
        seconds: 90,
        expPerSecond: 5.56,
        goldValue: 1250,
        goldPerSecond: 13.9,
    },
    {
        name: 'Watermelon',
        level: 50,
        exp: 850,
        seconds: 120,
        expPerSecond: 7.08,
        goldValue: 2000,
        goldPerSecond: 16.7,
    },
    {
        name: 'Grapes',
        level: 65,
        exp: 1100,
        seconds: 150,
        expPerSecond: 7.33,
        goldValue: 2500,
        goldPerSecond: 16.7,
    },
    {
        name: 'Papaya',
        level: 80,
        exp: 1250,
        seconds: 165,
        expPerSecond: 7.58,
        goldValue: 3250,
        goldPerSecond: 19.7,
    },
    {
        name: 'Dragon Fruit',
        level: 90,
        exp: 1500,
        seconds: 180,
        expPerSecond: 8.33,
        goldValue: 4000,
        goldPerSecond: 22.2,
    },
    {
        name: 'Sunfire Berry',
        level: 105,
        exp: 2850,
        seconds: 315,
        expPerSecond: 9.05,
        goldValue: 7500,
        goldPerSecond: 23.81,
    },
];
