import { SkillItem } from '@/types/calculator.types';

export const FORAGING_ITEMS: SkillItem[] = [
    {
        name: 'Nettle',
        level: 1,
        exp: 15,
        seconds: 6,
        expPerSecond: 2.5,
        goldValue: 7,
        goldPerSecond: 1.2,
    },
    {
        name: 'Kiwi Fruit',
        level: 10,
        exp: 20,
        seconds: 7,
        expPerSecond: 2.86,
        goldValue: 10,
        goldPerSecond: 1.4,
    },
    {
        name: 'Onion',
        level: 20,
        exp: 25,
        seconds: 7.5,
        expPerSecond: 3.33,
        goldValue: 12,
        goldPerSecond: 1.6,
    },
    {
        name: 'Magical Flax',
        level: 30,
        exp: 30,
        seconds: 8,
        expPerSecond: 3.75,
        goldValue: 15,
        goldPerSecond: 1.9,
    },
    {
        name: 'Blueberries',
        level: 40,
        exp: 36,
        seconds: 8,
        expPerSecond: 4.5,
        goldValue: 16,
        goldPerSecond: 2.0,
    },
    {
        name: 'Enchanted Flax',
        level: 55,
        exp: 44,
        seconds: 8.5,
        expPerSecond: 5.18,
        goldValue: 18,
        goldPerSecond: 2.1,
    },
    {
        name: 'Porcini',
        level: 70,
        exp: 60,
        seconds: 9,
        expPerSecond: 6.67,
        goldValue: 24,
        goldPerSecond: 2.7,
    },
    {
        name: 'Cursed Flax',
        level: 80,
        exp: 80,
        seconds: 10,
        expPerSecond: 8.0,
        goldValue: 34,
        goldPerSecond: 3.4,
    },
    {
        name: 'Seaweed',
        level: 90,
        exp: 110,
        seconds: 12.5,
        expPerSecond: 8.8,
        goldValue: 54,
        goldPerSecond: 4.3,
    },
    {
        name: 'Smoldering Mushroom',
        level: 105,
        exp: 210,
        seconds: 21.875,
        expPerSecond: 9.6,
        goldValue: 85,
        goldPerSecond: 3.89,
    },
];
