import { SkillItem } from '@/types/calculator.types';

export const WOODCUTTING_ITEMS: SkillItem[] = [
    {
        name: 'Spruce',
        level: 1,
        exp: 7.5,
        seconds: 3,
        expPerSecond: 2.5,
        goldValue: 6,
        goldPerSecond: 2.0,
    },
    {
        name: 'Pine',
        level: 10,
        exp: 14,
        seconds: 5,
        expPerSecond: 2.8,
        goldValue: 10,
        goldPerSecond: 2.0,
    },
    {
        name: 'Oak',
        level: 20,
        exp: 17.5,
        seconds: 6,
        expPerSecond: 2.92,
        goldValue: 13,
        goldPerSecond: 2.2,
    },
    {
        name: 'Maple',
        level: 30,
        exp: 20,
        seconds: 6.5,
        expPerSecond: 3.08,
        goldValue: 16,
        goldPerSecond: 2.5,
    },
    {
        name: 'Teak',
        level: 40,
        exp: 25,
        seconds: 8,
        expPerSecond: 3.13,
        goldValue: 20,
        goldPerSecond: 2.5,
    },
    {
        name: 'Chestnut',
        level: 50,
        exp: 35,
        seconds: 10,
        expPerSecond: 3.5,
        goldValue: 30,
        goldPerSecond: 3.0,
    },
    {
        name: 'Mahogany',
        level: 60,
        exp: 50,
        seconds: 12.5,
        expPerSecond: 4.0,
        goldValue: 40,
        goldPerSecond: 3.2,
    },
    {
        name: 'Yew',
        level: 70,
        exp: 67.5,
        seconds: 15,
        expPerSecond: 4.5,
        goldValue: 55,
        goldPerSecond: 3.7,
    },
    {
        name: 'Redwood',
        level: 80,
        exp: 90,
        seconds: 17.5,
        expPerSecond: 5.14,
        goldValue: 75,
        goldPerSecond: 4.3,
    },
    {
        name: 'Magical',
        level: 90,
        exp: 110,
        seconds: 20,
        expPerSecond: 5.5,
        goldValue: 110,
        goldPerSecond: 5.5,
    },
    {
        name: 'Ignis',
        level: 105,
        exp: 935,
        seconds: 150,
        expPerSecond: 6.23,
        goldValue: 150,
        goldPerSecond: 1.0,
    },
];
